'use client';

import { useState } from 'react';
import type { Metadata } from 'next';
import { usePathname } from 'next/navigation';
import Navbar from './navbar';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const disableNavbar: Array<string> = ['/login', '/register'];

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app'
// };

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [state, setState] = useState<number>(0);
    const pathName = usePathname();
    return (
        <html lang='en'>
            <body className={inter.className}>
                {!disableNavbar.includes(pathName) && <Navbar />}
                {/*<div>
                    <h1>Layout {state}</h1>
                    <button
                        onClick={() => {
                            setState(state + 1);
                        }}
                    >
                        click
                    </button>
                </div>*/}
                {children}
            </body>
        </html>
    );
}
