'use client';

import { useState } from 'react';
import type { Metadata } from 'next';
import { usePathname } from 'next/navigation';
import Navbar from './navbar';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const disableNavbar: Array<string> = ['/login', '/register'];

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app'
// };

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathName = usePathname();
    return (
        <html lang='en'>
            <body
                className={`${inter.className} w-full min-h-screen bg-white dark:bg-gray-950`}
            >
                <SessionProvider>
                    {!disableNavbar.includes(pathName) && <Navbar />}
                    {children}
                </SessionProvider>
            </body>
        </html>
    );
}
